language: node_js
node_js:
  - 0.10

env:
  global:
    - LOGS_DIR=/tmp/angular-build/logs

before_script:
  - mkdir -p $LOGS_DIR
  - npm install -g grunt-cli
  - grunt -d --stack bower

script:
  - ./travis_build.sh

after_script:
  - ./travis_print_logs.sh

